# Generated by Django 4.0.6 on 2022-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('ORDER_NUMBER', models.IntegerField()),
                ('PRICE_USD', models.IntegerField()),
                ('SUPPLY_DATE', models.DateField()),
                ('PRICE_RUB', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'ordering': ['ID'],
            },
        ),
    ]
